version: '3.8'

services:
  # Backend API service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_change_me_in_production}
      - JWT_EXPIRATION=1d
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-password}@db:5432/telemedix
    depends_on:
      - db
    networks:
      - telemedix-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    # WICHTIG: Für Produktionsumgebungen diesen command-Block entfernen oder auskommentieren!
    # Dieser Teil ist nur für die Entwicklung gedacht, um die Datenbank automatisch zu initialisieren
    command: >
      sh -c "
        sleep 5 &&
        npx prisma db push --force-reset &&
        npx prisma db seed &&
        npm start
      "

  # Frontend web service
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000/api
    networks:
      - telemedix-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Database service
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=telemedix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telemedix-network

# Volume for database persistence
volumes:
  postgres_data:

# Network for container communication
networks:
  telemedix-network:
    driver: bridge 